# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado/ECOP-18340161-03/ECOP-18340161-03.cache/wt [current_project]
set_property parent.project_path E:/vivado/ECOP-18340161-03/ECOP-18340161-03.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/upDatePC.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/SignZeroExtend.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/SelectRegDst.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/Register_Files.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/PC.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/Instruction_Memory.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/Instruction_divid.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/Data_Memory.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/DataSelect.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/ALUSourcrA_Select.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/ALU.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/Control_Unit.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/SegLED.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/key_vibration.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/SingleCyleCPU.v
  E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/sources_1/new/Basys3.v
}
read_xdc E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/constrs_1/new/my.xdc
set_property used_in_implementation false [get_files E:/vivado/ECOP-18340161-03/ECOP-18340161-03.srcs/constrs_1/new/my.xdc]

synth_design -top Basys3 -part xc7a35tcpg236-1
write_checkpoint -noxdef Basys3.dcp
catch { report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb }
